# Generated by Django 5.0.1 on 2026-01-24 11:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emailverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=api.models.get_today),
        ),
    ]
