# Generated by Django 5.2.9 on 2026-02-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_creditcard_number_alter_user_join_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="CreditCard",
        ),
    ]
